### ISSUE TITLE
Create Droplet - User Data

### ISSUE THREAD

**Issue by jaredbroad** [trmcnvn/DigitalOcean.API#10]
Please add support for user_data on droplet creation

**Comment by vevix** [comment]
I've been meaning to update this library for awhile now, unfortunately I doubt I'll be able to get to this within the next 2 weeks. You're welcome to create a PR if you would like this change earlier.

**Comment by jaredbroad** [comment]
Thanks Thomas, I took a look -- its as simple as adding it to the droplet
request model right?

On Sat, Aug 22, 2015 at 8:56 AM, Thomas McNiven <notifications@github.com>
wrote:

> I've been meaning to update this library for awhile now, unfortunately I
> doubt I'll be able to get to this within the next 2 weeks. You're welcome
> to create a PR if you would like this change earlier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vevix/DigitalOcean.API/issues/10#issuecomment-133699809>
> .
>



-- 
Jared Broad

**Comment by vevix** [comment]
Yep  I believe that is all that will be needed.

**Comment by trmcnvn** [comment]
This was added in e11f7d2
