### ISSUE TITLE
[PR Consideration] Type changes for Request/Response Models

### ISSUE THREAD

**Issue by Nicholi** [trmcnvn/DigitalOcean.API#36]
Since you just made the version 3 bump change, I am guessing from the minor API breakage in renaming the `TTL`  to `Ttl` properties, I'd like to start consideration for possible type changes from 2.x. Mostly would like to know if you would be amenable to a detailed audit of all the current Request/Response models in the form of a PR. Possibly also considering any name inconsistencies like the TTL/Ttl thing.

Some of the things I am thinking of:
1. All ValueTypes properties in Request models should be marked as Nullable if they are **not required** in the request. I have seem semi-inconsistent notation in some of the Request models, some marking their ints/floats/bools as Nullable and others not. Ones I've already noticed would be the booleans in `Models.Requests.Droplet`: backups, ipv6, private_networking, monitoring. Obviously this would cause no "real change", as the defaults for all these when unsent is false and the default value for any boolean is false anyways in C#. But would seem like an appropriate time for a consistency fix.

2. Changing the types from float to Decimal for `PriceMonthly` and `PriceHourly` in `Models.Responses.Sizes`. As these values are specifically for currencies, Decimal would seem more appropriate in my mind.

I haven't really looked through too many of the classes that closely, but other things might come up.

**Comment by trmcnvn** [comment]
Definitely agree with both of these points and would be happy for PRs to address them.

**Comment by Nicholi** [comment]
Closed from https://github.com/trmcnvn/DigitalOcean.API/commit/23c279e151a3737c751b69c3a5b3674374e82449
