### ISSUE TITLE
Equal name class in different namespace

### ISSUE THREAD

**Issue by podobaas** [trmcnvn/DigitalOcean.API#70]
Thanks for this library! :)

I use this library in my project, but I have difficulties because the same names for the request and response classes, albeit in different namespaces. Often it is necessary to use the request and response class in the same class. 
It turns out 2 options: 
1) Use alias 
2) Use the full name of the type. 

All these 2 options impair code reading. Could it be better to use endings in classes? 

`Task<DigitalOcean.API.Models.Responses.Action>>` and etc

For example:
ActionRq - request
ActionRs - response 

OR

ActionRequest
ActionResponse

**Comment by trmcnvn** [comment]
I personally think aliasing is a fine solution to this.

```csharp
using Requests = DigitalOcean.API.Models.Requests;
using Responses = DigitalOcean.API.Models.Responses;

Requests.Action
Responses.Action
```

**Comment by podobaas** [comment]
Ok) Thanks for reply
